export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const UPDATE_CUSTOMER = 'EDIT_CUSTOMER';

export const CREATE_GROUP = 'CREATE_GROUP';
export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUP = 'FETCH_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';

export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

export const CREATE_VIDEO = 'CREATE_VIDEO';
export const FETCH_VIDEOS = 'FETCH_VIDEOS';
export const FETCH_VIDEO = 'FETCH_VIDEO';
export const DELETE_VIDEO = 'DELETE_VIDEO';
export const UPDATE_VIDEO = 'UPDATE_VIDEO';
export const FETCH_IMDB_VIDEO = 'FETCH_IMDB_VIDEO';
export const CLEAR_IMDB_VIDEO = 'CLEAR_IMDB_VIDEO';

export const CREATE_COPY = 'CREATE_COPY';
export const FETCH_COPIES = 'FETCH_COPIES';
export const FETCH_COPY = 'FETCH_COPY';
export const DELETE_COPY = 'DELETE_COPY';
export const UPDATE_COPY = 'UPDATE_COPY';

export const CALCULATE_RENTAL = 'CALCULATE_RENTAL';
export const FETCH_RENTAL = 'FETCH_RENTAL';
export const RENT_VIDEO = 'RENT_VIDEO';
export const RETURN_VIDEO = 'RETURN_VIDEO';
export const SETTLE_RENTAL = 'SETTLE_RENTAL';

export const CATCH_ERROR = 'CATCH_ERROR';
export const DISMISS_ERROR = 'DISMISS_ERROR';